version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-networks

networks:
  app-networks:
    driver: bridge
